### ISSUE TITLE
[wontfix] The truth of engineering correctness

### ISSUE THREAD

**Issue by LukeXuan** [tripack45/VE280-Notes#1]
While testing did indeed help your code to behave correctly in most cases. It never gives full assurance. I think you should recommend the technology of formal methods, especially verification, to introduce the possibility of complete correctness of program to students.

**Comment by tripack45** [comment]
I will remember to quote these words in my next lectrure.

**Comment by JasonQSY** [comment]
@tripack45 I think [this](https://www.ralfj.de/blog/2017/06/09/mutexguard-sync.html) could be a good evidence to show the power of LukeXuan and formal methods.

**Comment by tripack45** [comment]
@JasonQSY You do know there is a reason why I call this chapter "Engineering Correctness", not "ensuring correctness", right? I guess the word "engineering" already conveyed necessary information.

**Comment by LukeXuan** [comment]
In my understanding, what means by engineering correctness should be practical methods. Actually, decades earlier in Paris, the metro No. 14 is **formally verified** for its automatic system with B-method. The **bias** that formal methods is not practical in terms of cost is not practical now.

**Comment by tripack45** [comment]
Practical also means easily applicable to the context. I would argue that formal methods simply doesn't apply to our context. On the other hand I guess the reason that formal methods doesn't popularize after Paris line 14. implies that this is not "practical". Please do remember engineering is both an art of utilizing technology and an art of weighing cost against gain.
